In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing


In [2]:
data= pd.read_csv('marketing_customer_analysis.csv')
data

Customer       State  Customer Lifetime Value Response  Coverage  \
0     BU79786  Washington              2763.519279       No     Basic   
1     QZ44356     Arizona              6979.535903       No  Extended   
2     AI49188      Nevada             12887.431650       No   Premium   
3     WW63253  California              7645.861827       No     Basic   
4     HB64268  Washington              2813.692575       No     Basic   
...       ...         ...                      ...      ...       ...   
9129  LA72316  California             23405.987980       No     Basic   
9130  PK87824  California              3096.511217      Yes  Extended   
9131  TD14365  California              8163.890428       No  Extended   
9132  UP19263  California              7524.442436       No  Extended   
9133  Y167826  California              2611.836866       No  Extended   

     Education Effective To Date EmploymentStatus Gender  Income  ...  \
0     Bachelor           2/24/11         Employed      F   56274  ...   
1     Bachelor           1/31/11       Unemployed      F       0  ...   
2     Bachelor           2/19/11         Employed      F   48767  ...   
3     Bachelor           1/20/11       Unemployed      M       0  ...   
4     Bachelor            2/3/11         Employed      M   43836  ...   
...        ...               ...              ...    ...     ...  ...   
9129  Bachelor           2/10/11         Employed      M   71941  ...   
9130   College           2/12/11         Employed      F   21604  ...   
9131  Bachelor            2/6/11       Unemployed      M       0  ...   
9132   College            2/3/11         Employed      M   21941  ...   
9133   College           2/14/11       Unemployed      M       0  ...   

     Months Since Policy Inception Number of Open Complaints  \
0                                5                         0   
1                               42                         0   
2                               38                         0   
3                               65                         0   
4                               44                         0   
...                            ...                       ...   
9129                            89                         0   
9130                            28                         0   
9131                            37                         3   
9132                             3                         0   
9133                            90                         0   

      Number of Policies     Policy Type        Policy  Renew Offer Type  \
0                      1  Corporate Auto  Corporate L3            Offer1   
1                      8   Personal Auto   Personal L3            Offer3   
2                      2   Personal Auto   Personal L3            Offer1   
3                      7  Corporate Auto  Corporate L2            Offer1   
4                      1   Personal Auto   Personal L1            Offer1   
...                  ...             ...           ...               ...   
9129                   2   Personal Auto   Personal L1            Offer2   
9130                   1  Corporate Auto  Corporate L3            Offer1   
9131                   2  Corporate Auto  Corporate L2            Offer1   
9132                   3   Personal Auto   Personal L2            Offer3   
9133                   1  Corporate Auto  Corporate L3            Offer4   

      Sales Channel Total Claim Amount  Vehicle Class Vehicle Size  
0             Agent         384.811147   Two-Door Car      Medsize  
1             Agent        1131.464935  Four-Door Car      Medsize  
2             Agent         566.472247   Two-Door Car      Medsize  
3       Call Center         529.881344            SUV      Medsize  
4             Agent         138.130879  Four-Door Car      Medsize  
...             ...                ...            ...          ...  
9129            Web         198.234764  Four-Door Car      Medsize  
9130         Bran

In [3]:
numerical = data.select_dtypes([np.number])
numerical

Customer Lifetime Value  Income  Monthly Premium Auto  \
0                 2763.519279   56274                    69   
1                 6979.535903       0                    94   
2                12887.431650   48767                   108   
3                 7645.861827       0                   106   
4                 2813.692575   43836                    73   
...                       ...     ...                   ...   
9129             23405.987980   71941                    73   
9130              3096.511217   21604                    79   
9131              8163.890428       0                    85   
9132              7524.442436   21941                    96   
9133              2611.836866       0                    77   

      Months Since Last Claim  Months Since Policy Inception  \
0                          32                              5   
1                          13                             42   
2                          18                             38   
3                          18                             65   
4                          12                             44   
...                       ...                            ...   
9129                       18                             89   
9130                       14                             28   
9131                        9                             37   
9132                       34                              3   
9133                        3                             90   

      Number of Open Complaints  Number of Policies  Total Claim Amount  
0                             0                   1          384.811147  
1                             0                   8         1131.464935  
2                             0                   2          566.472247  
3                             0                   7          529.881344  
4                             0                   1          138.130879  
...                         ...                 ...                 ...  
9129                          0                   2          198.234764  
9130                          0                   1          379.200000  
9131                          3                   2          790.784983  
9132                          0                   3          691.200000  
9133                          0                   1          369.600000  

[9134 rows x 8 columns]

In [4]:
categoricals = data.select_dtypes(include=['object'])
categoricals

Customer       State Response  Coverage Education Effective To Date  \
0     BU79786  Washington       No     Basic  Bachelor           2/24/11   
1     QZ44356     Arizona       No  Extended  Bachelor           1/31/11   
2     AI49188      Nevada       No   Premium  Bachelor           2/19/11   
3     WW63253  California       No     Basic  Bachelor           1/20/11   
4     HB64268  Washington       No     Basic  Bachelor            2/3/11   
...       ...         ...      ...       ...       ...               ...   
9129  LA72316  California       No     Basic  Bachelor           2/10/11   
9130  PK87824  California      Yes  Extended   College           2/12/11   
9131  TD14365  California       No  Extended  Bachelor            2/6/11   
9132  UP19263  California       No  Extended   College            2/3/11   
9133  Y167826  California       No  Extended   College           2/14/11   

     EmploymentStatus Gender Location Code Marital Status     Policy Type  \
0            Employed      F      Suburban        Married  Corporate Auto   
1          Unemployed      F      Suburban         Single   Personal Auto   
2            Employed      F      Suburban        Married   Personal Auto   
3          Unemployed      M      Suburban        Married  Corporate Auto   
4            Employed      M         Rural         Single   Personal Auto   
...               ...    ...           ...            ...             ...   
9129         Employed      M         Urban        Married   Personal Auto   
9130         Employed      F      Suburban       Divorced  Corporate Auto   
9131       Unemployed      M      Suburban         Single  Corporate Auto   
9132         Employed      M      Suburban        Married   Personal Auto   
9133       Unemployed      M      Suburban         Single  Corporate Auto   

            Policy Renew Offer Type Sales Channel  Vehicle Class Vehicle Size  
0     Corporate L3           Offer1         Agent   Two-Door Car      Medsize  
1      Personal L3           Offer3         Agent  Four-Door Car      Medsize  
2      Personal L3           Offer1         Agent   Two-Door Car      Medsize  
3     Corporate L2           Offer1   Call Center            SUV      Medsize  
4      Personal L1           Offer1         Agent  Four-Door Car      Medsize  
...            ...              ...           ...            ...          ...  
9129   Personal L1           Offer2           Web  Four-Door Car      Medsize  
9130  Corporate L3           Offer1        Branch  Four-Door Car      Medsize  
9131  Corporate L2           Offer1        Branch  Four-Door Car      Medsize  
9132   Personal L2           Offer3        Branch  Four-Door Car        Large  
9133  Corporate L3           Offer4   Call Center   Two-Door Car      Medsize  

[9134 rows x 16 columns]

In [5]:
numerical.corr(method='spearman')

Customer Lifetime Value    Income  \
Customer Lifetime Value                       1.000000  0.055395   
Income                                        0.055395  1.000000   
Monthly Premium Auto                          0.453933 -0.017608   
Months Since Last Claim                       0.005126 -0.025784   
Months Since Policy Inception                -0.002429 -0.001945   
Number of Open Complaints                    -0.031312  0.006334   
Number of Policies                            0.488860 -0.010273   
Total Claim Amount                            0.210598 -0.401598   

                               Monthly Premium Auto  Months Since Last Claim  \
Customer Lifetime Value                    0.453933                 0.005126   
Income                                    -0.017608                -0.025784   
Monthly Premium Auto                       1.000000                -0.005989   
Months Since Last Claim                   -0.005989                 1.000000   
Months Since Policy Inception              0.014596                -0.048269   
Number of Open Complaints                 -0.012751                 0.005736   
Number of Policies                        -0.006936                 0.011439   
Total Claim Amount                         0.522261                -0.000782   

                               Months Since Policy Inception  \
Customer Lifetime Value                            -0.002429   
Income                                             -0.001945   
Monthly Premium Auto                                0.014596   
Months Since Last Claim                            -0.048269   
Months Since Policy Inception                       1.000000   
Number of Open Complaints                          -0.013233   
Number of Policies                                 -0.009546   
Total Claim Amount                                 -0.006569   

                               Number of Open Complaints  Number of Policies  \
Customer Lifetime Value                        -0.031312            0.488860   
Income                                          0.006334           -0.010273   
Monthly Premium Auto                           -0.012751           -0.006936   
Months Since Last Claim                         0.005736            0.011439   
Months Since Policy Inception                  -0.013233           -0.009546   
Number of Open Complaints                       1.000000            0.001523   
Number of Policies                              0.001523            1.000000   
Total Claim Amount                             -0.024694           -0.011100   

                               Total Claim Amount  
Customer Lifetime Value                  0.210598  
Income                                  -0.401598  
Monthly Premium Auto                     0.522261  
Months Since Last Claim                 -0.000782  
Months Since Policy Inception           -0.006569  
Number of Open Complaints               -0.024694  
Number of Policies                      -0.011100  
Total Claim Amount                       1.000000

In [6]:
X = numerical.drop(['Total Claim Amount'], axis=1)
y = numerical['Total Claim Amount']


In [7]:
for col in numerical:
    x_array = np.array(numerical[col])
    normalized_arr = preprocessing.normalize([x_array])
    print(normalized_arr)

[[0.00274104 0.00692276 0.0127826  ... 0.00809748 0.00746324 0.00259059]]
[[0.01216983 0.         0.01054636 ... 0.         0.00474497 0.        ]]
[[0.00726575 0.00989827 0.01137248 ... 0.00895056 0.01010887 0.00810816]]
[[0.01844895 0.00749489 0.01037753 ... 0.00518877 0.01960201 0.00172959]]
[[0.00094133 0.00790714 0.00715408 ... 0.00696581 0.0005648  0.01694387]]
[[0.         0.         0.         ... 0.03176605 0.         0.        ]]
[[0.00274681 0.02197446 0.00549361 ... 0.00549361 0.00824042 0.00274681]]
[[0.00770875 0.02266612 0.01134788 ... 0.01584143 0.01384649 0.00740403]]
